Repository InseeFr/Lunatic, pull requests merged in 2023-08, with the labels that each got.

#567 Allow page tag for goToPage()
  e2e/simpson.spec.ts
  package.json
  src/components/commons/create-row-orchestrator.tsx
  src/components/roundabout/lunatic-roundabout.tsx
  src/stories/utils/orchestrator.jsx
  src/use-lunatic/commons/check-pager.ts
  src/use-lunatic/commons/page-navigation.spec.ts
  src/use-lunatic/commons/page-navigation.ts
  src/use-lunatic/commons/page.ts
  src/use-lunatic/reducer/commons/auto-explore-loop.ts
  src/use-lunatic/reducer/commons/index.ts
  src/use-lunatic/reducer/commons/is-empty-on-empty-page.ts
  src/use-lunatic/reducer/reduce-go-next-page.ts
  src/use-lunatic/reducer/reduce-go-previous-page.ts
  src/use-lunatic/reducer/reduce-go-to-page.ts
  src/use-lunatic/reducer/reduce-roundabout.ts
  src/use-lunatic/type.ts
Labels: enhancement, ready for review

#623 Fix/last reached page
  README.md
  sonar-project.properties
  src/components/loop/block-for-loop/block-for-loop.tsx
  src/components/modal-controls/modal-controls.tsx
  src/components/table/table-orchestrator.tsx
  src/stories/utils/orchestrator.jsx
  src/use-lunatic/actions.ts
  src/use-lunatic/commons/execute-expression/create-refresh-calculated.spec.ts
  src/use-lunatic/commons/index.ts
  src/use-lunatic/commons/load-suggesters.js
  src/use-lunatic/reducer/reduce-on-init.ts
  src/use-lunatic/use-lunatic.test.ts
  src/use-lunatic/use-lunatic.ts
  src/utils/store-tools/auto-load.ts
Labels: enhancement, easy-review

#633 Allow custom ComboBoxContent
  .gitignore
  src/components/commons/components/combo-box/combo-box-container.spec.tsx
  src/components/commons/components/combo-box/combo-box-container.tsx
  src/components/commons/components/combo-box/combo-box-content-box.tsx
  src/components/commons/components/combo-box/combo-box-content.tsx
  src/components/commons/components/combo-box/combo-box.tsx
  src/components/commons/components/combo-box/panel/panel-container.spec.tsx
  src/components/commons/components/combo-box/panel/panel-container.tsx
  src/components/commons/components/combo-box/panel/panel.tsx
  src/components/commons/components/combo-box/selection/selection-container.tsx
  src/components/commons/components/combo-box/selection/selection.tsx
  src/components/suggester/html/suggester.tsx
  src/components/suggester/lunatic-suggester.tsx
  src/stories/suggester/simple.json
Labels: easy-review

#638 Fix: disabled suggester
  src/components/commons/components/combo-box/combo-box.tsx
Labels: easy-review
